### ISSUE TITLE
При повторном вызове get_access_token в obj записывается след.

### ISSUE THREAD

**Issue by SimonGyrin** [Fsoky/Donation-Alerts-API-Python#10]
![изображение](https://github.com/Fsoky/DonationAlertsAPI/assets/55016616/dcfd87e2-1471-476a-ad6c-911e958d4617)

**Comment by SimonGyrin** [comment]
можно накостылить и сделать так, чтобы obj записывался в глобальную один раз))
ну если это всё баг конечно

**Comment by Fsoky** [comment]
#11
