### ISSUE TITLE
asyncio_api не позволяет работать одновременно с другими асинхронными модулями

### ISSUE THREAD

**Issue by shardeex** [Fsoky/Donation-Alerts-API-Python#2]
В donationalerts_api/asyncio_api.py жёстко прописан запуск лишь одной корунтины — хэндлера ивентов

```
loop = asyncio.get_event_loop()
loop.run_until_complete(wrapper())
return loop.run_forever()
```

Потому если я буду работать также с другой библиотекой (основной библиотекой для моего бота, например), то я не смогу одновременно запустить хэндлер событий бота и хэндлер событий донатов. Возможно, стоит возвращать не уже запущенную корунтину, а лишь подготавливать её к запуску?

**Comment by shardeex** [comment]
Наверное, решение слишком очевидное и просто, сделал пулл реквест. #3

**Comment by shardeex** [comment]
Отмена, не работает. Хотелось бы решить проблему.

**Comment by SayHelloRoman** [comment]
Запускай второй event loop в дочернем процессе.
